version: "3"
services:
  db:
    image: mongo:latest
    container_name: mongo
    ports: 
        - 27017:27017
    volumes:
        - /var/lib/mongodb/:/var/lib/mongodb
    restart: always
    
  backend:
    image: linkshortener
    container_name: linkshortener
    ports:
        - 8080:8080
    environment:
        CONFIG_PATH: config/server_container.toml
    restart: always
    depends_on: 
        - db
    