version: "3"
services:
  db:
    image: mongo:latest
    container_name: mongo
    ports: 
        - 27017:27017
    volumes:
        - ./mongodb_data:/var/lib/mongodb
    # environment:
    #     DATABASE_NAME: linkshortener
    #     COLLECTION_NAME: links
    #     MONGODB_CONNECTION: mongodb://localhost:27017
    restart: always
  app:
    image: golang:latest
    container_name: linkshortener
    ports:
        - 8080:8080
    environment:
        # BIND_ADDR: 8080
        # SHORT_URL_LENGTH: 7
        CONFIG_PATH: config/server.toml
    restart: always
    depends_on: 
        - db
    