version: "3"
services:
  db:
    image: mongodb:latest
    container_name: mongo
    ports: 
        - 27017:27017
    volumes:
        - ./mongodb_data:/var/lib/mongodb
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: 123