version: "3"
services:
  db:
    image: mongo:latest
    container_name: mongo
    ports: 
        - 27017:27017
    volumes:
        # - /var/lib/mongodb/:/var/lib/mongodb
        - ./mongoinit/mongoinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    logging: 
        driver: "none"
    restart: always
    
  backend:
    image: linkshortener
    build:
        context: .
    container_name: linkshortener
    ports:
        - 8080:8080
    environment:
        BIND_ADDR: :8080
        SHORTURL_LENGTH: 7
        MONGODB_CONN: mongodb://db:27017
        DBNAME: linkshortener
        COLLECTION_NAME: links
    restart: always
    depends_on: 
        - db
    